### ISSUE TITLE
UBI9/RHEL9 ansible-operator based images

### ISSUE THREAD

**Issue by fbladilo** [openshift/ocp-release-operator-sdk#322]
#### Describe the problem you need a feature to resolve.

The currently supplied base images for ansible-operator are still all RHEL8 based , many products are moving their base images to rhel9 including ours but there isn't  a matching ubi9/rhel9 build available. 

[fbladilo@fdev:~/release/cpaas/mta/versions/release-6.2.0] (relocate_operator =)$ docker run --rm -it --entrypoint /bin/bash registry.redhat.io/openshift4/ose-ansible-operator:latest

bash-4.4$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.6 (Ootpa)
bash-4.4$ 

#### Describe the solution you'd like.

A RHEL9 based ansible-operator to be supplied along with the existing rhel8 release. 

/language ansible

**Comment by leifmadsen** [comment]
This will take some work, but some clean up and updating that we're working on now should start to clear the way for this, perhaps in the OCP 4.15 timeframe.

**Comment by leifmadsen** [comment]
> 4.14 would be really useful if it could be backported.

I agree but backporting this to 4.14 would be quite invasive as it would switch the ansible version along with the underlying base image, potentially causing incompatibility with existing operators.

My opinion here is that backporting to 4.14 is not really feasible. I don't believe there should be anything stopping an operator developer from using a base image tagged with 4.15 on the 4.14 platform though.

**Comment by leifmadsen** [comment]
> 100% agree. Actually I believe the 4.15 image should be the image for 4.14 as well. No need to change ansible version etc. As there will be no 4.14 rhel9/ansible version otherwise.

I'm not sure what you mean by "the 4.15 image should be the image for 4.14 as well". I do not believe the 4.15 image will be tagged for 4.14. The ose-ansible-operator image for 4.14 will be UBI8 base image + Ansible 2.15.

The base image for 4.15 or 4.16 is expected to target UBI9 + Ansible-{recent}. If an Operator developer wishes to use 4.15 (or later) image on top of 4.14 I don't see an issue with that. Obviously testing by the developer will be required to verify this for their scenario.

To be clear, I do not expect any ose-ansible-operator:4.14 tagged image to be anything other than UBI8 + Ansible 2.15 as that is what exists in the product pipeline. Alignment to a new base image is for a future tagged release.
